# Generated by Django 6.0.2 on 2026-02-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='picture_url',
            field=models.URLField(blank=True),
        ),
    ]
