# Generated by Django 6.0.2 on 2026-02-28 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0002_remove_authorprofile_user_author_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='author',
            name='unique_user_host',
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('display_name', 'host'), name='unique_display_name_host'),
        ),
        migrations.RemoveField(
            model_name='author',
            name='profile_url',
        ),
        migrations.RemoveField(
            model_name='author',
            name='website_url',
        ),
    ]
