# Generated by Django 6.0.2 on 2026-02-23 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0003_merge_20260221_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('LOCAL', 'Local'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted')], default='LOCAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='socialdistribution.author')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
