# Generated by Django 6.0.2 on 2026-02-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0004_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content_type',
            field=models.CharField(choices=[('text/markdown', 'CommonMark'), ('text/plain', 'Plain Text')], default='text/plain', max_length=20),
        ),
    ]
