# Generated by Django 6.0.2 on 2026-02-25 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0005_entry_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_entries', to='socialdistribution.author'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='socialdistribution.author')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='socialdistribution.entry')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to='socialdistribution.author')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
