# Generated by Django 6.0.2 on 2026-02-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0006_entry_likes_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
