# Generated by Django 6.0.2 on 2026-02-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0007_alter_entry_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted')], default='PUBLIC', max_length=10),
        ),
    ]
