# Generated by Django 6.0.2 on 2026-02-28 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0008_alter_entry_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_events', to='socialdistribution.author')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('author', 'event_id'), name='unique_author_event')],
            },
        ),
    ]
