# Generated by Django 6.0.2 on 2026-02-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0010_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='seen_by_target',
            field=models.BooleanField(default=False),
        ),
    ]
